// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppConfigService manages app-level configuration (recent worlds list).
 * Config is persisted at the OS user config directory:
 *   - Windows: %APPDATA%/LitGuardian/config.json
 *   - macOS:   ~/Library/Application Support/LitGuardian/config.json
 *   - Linux:   ~/.config/LitGuardian/config.json
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddRecentWorld upserts a world entry by path, updates LastOpened, caps the
 * list at maxRecentWorlds, and persists to disk.
 */
export function AddRecentWorld(name: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(2414822812, name, path);
}

/**
 * GetRecentWorlds returns the recent worlds list sorted by LastOpened descending.
 */
export function GetRecentWorlds(): $CancellablePromise<$models.WorldInfo[]> {
    return $Call.ByID(853707434).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RemoveRecentWorld removes a world entry by path and persists to disk.
 */
export function RemoveRecentWorld(path: string): $CancellablePromise<void> {
    return $Call.ByID(3533838737, path);
}

// Private type creation functions
const $$createType0 = $models.WorldInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
