// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../time/models.js";

/**
 * WorldInfo describes a recently opened world entry stored in app config.
 */
export class WorldInfo {
    "name": string;
    "path": string;
    "lastOpened": time$0.Time;

    /** Creates a new WorldInfo instance. */
    constructor($$source: Partial<WorldInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("lastOpened" in $$source)) {
            this["lastOpened"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorldInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): WorldInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorldInfo($$parsedSource as Partial<WorldInfo>);
    }
}
