// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorldService handles world folder operations and the native OS folder picker.
 * It is stateless — all data lives on disk, no in-memory cache.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateWorld scaffolds a new world at folderPath with the given name.
 * It creates: world.json, entities/, links.json, tags.json, categories.json.
 * Returns a WorldInfo suitable for adding to the recents list.
 */
export function CreateWorld(name: string, folderPath: string): $CancellablePromise<$models.WorldInfo | null> {
    return $Call.ByID(613081143, name, folderPath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * OpenWorld validates that folderPath is a valid world (contains world.json),
 * reads the world name from disk, and returns a WorldInfo suitable for adding
 * to the recents list. Returns a user-friendly error if world.json is absent.
 */
export function OpenWorld(folderPath: string): $CancellablePromise<$models.WorldInfo | null> {
    return $Call.ByID(147405563, folderPath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SelectFolder opens the native OS directory picker and returns the selected path,
 * or an empty string if the user cancelled without selecting.
 */
export function SelectFolder(): $CancellablePromise<string> {
    return $Call.ByID(4220090729);
}

// Private type creation functions
const $$createType0 = $models.WorldInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
