// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject() {
  return window['go']['project']['ApplicationManager']['CreateProject']();
}

export function GetConfig() {
  return window['go']['project']['ApplicationManager']['GetConfig']();
}
