// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateProject(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1071473426) as any;
    return $resultPromise;
}

export function GetConfig(): Promise<$models.ApplicationConfig> & { cancel(): void } {
    let $resultPromise = $Call.ByID(190472377) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function OpenProject(projectId: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3122778702, projectId) as any;
    return $resultPromise;
}

export function OpenProjectFolder(folder: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(700617598, folder) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.ApplicationConfig.createFrom;
