// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function EditTagName(oldName: string, newName: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3786420214, oldName, newName) as any;
    return $resultPromise;
}

export function RemoveTag(tagName: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2540430597, tagName) as any;
    return $resultPromise;
}
